### ISSUE TITLE
environment variable not set on `windows-latest` using PowerShell 7

### ISSUE THREAD

**Issue by ghost** [mtkennerly/dunamai-action#1]
workflow run example where variable `VERSION` appears not to have been set (in the `Retrieve version from repository` step):
[failed run](https://github.com/noaa-ocs-modeling/nemspy/runs/1155202382?check_suite_focus=true)
[workflow file](https://github.com/noaa-ocs-modeling/nemspy/actions/runs/268824188/workflow#L56)

**Comment by ghost** [comment]
looking at the code this actually looks like a problem with [`exportVariable`](https://github.com/actions/toolkit/blob/1cc56db0ff126f4d65aeb83798852e02a2c180c3/packages/core/src/core.ts#L39) in `@actions/core`

**Comment by mtkennerly** [comment]
I recently ran into an issue where `echo ::warning::foo: bar` only logged `foo:` on Windows (expected output: `foo: bar`), until I added `shell: bash` to the workflow. Could you try that as a temporary workaround? (I didn't have to do any special setup for it to be able to use Bash on Windows, so I assume it's taken care of by the runner config.)

But yeah, I agree this sounds like an issue either in the actions library or with the underlying `set-env` workflow command. I'll add some tests here to see if I can reproduce it, and if I can, then I'll report it to GitHub.

**Comment by ghost** [comment]
yep, [using `shell: bash` worked perfectly](https://github.com/noaa-ocs-modeling/nemspy/runs/1162675002?check_suite_focus=true), I dunno why I didn't think of that. Thanks for the help, and for making an awesome version parser!

**Comment by mtkennerly** [comment]
I just realized what the issue was because I had the same issue in my Windows test. PowerShell requires `$env:MY_VERSION` instead of just `$MY_VERSION`. If you change that, it should work fine.

Coincidentally, GitHub recently decided to deprecate `set-env` in favor of another implementation: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands . I've also updated the action, so you won't get any deprecation warnings from that.
